schedule_planner_be/api/location/urls.py
from rest_framework.routers import SimpleRouter
from api.location.views import LocationViewSet


router = SimpleRouter()
router.register('', LocationViewSet)
urlpatterns = router.urls

schedule_planner_be/api/urls.py
from django.urls import path, include


urlpatterns = [
    path('', include('api.user.urls')),
    path('teachers/', include('api.teacher.urls')),
    path('courses/', include('api.course.urls')),
    path('locations/', include('api.location.urls')),
    path('classrooms/', include('api.classroom.urls')),
    path('subwaystations/', include('api.subwaystation.urls')),
    path('comments/', include('api.comment.urls')),
    path('lessons/', include('api.lesson.urls'))
]

schedule_planner_be/schedule/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('schedules/', views.ScheduleListView.as_view(), name='schedules'),
    path('schedule/<int:pk>/detail', views.ScheduleDetailView.as_view(), name='schedule-detail'),
    path('add-schedule/', views.ScheduleCreateView.as_view(), name='add-schedule'),
    path('delete-schedule/<int:pk>/delete', views.ScheduleDeleteView.as_view(), name='delete-schedule'),
    path('edit-schedule/<int:pk>/update', views.ScheduleUpdateView.as_view(), name='edit-schedule'),
]

urlpatterns += [
    path('locations/', views.LocationListView.as_view(), name='locations'),
    path('location/<int:pk>/detail', views.LocationDetailView.as_view(), name='location-detail'),
    path('add-location/', views.LocationCreateView.as_view(), name='add-location'),
    path('delete-location/<int:pk>/delete', views.LocationDeleteView.as_view(), name='delete-location'),
    path('edit-location/<int:pk>/update', views.LocationUpdateView.as_view(), name='edit-location'),
]

urlpatterns += [
    path('subways/', views.SubwayStationListView.as_view(), name='subways'),
    path('subway/<int:pk>/detail', views.SubwayStationDetailView.as_view(), name='subway-detail'),
    path('add-subway/', views.SubwayStationCreateView.as_view(), name='add-subway'),
    path('delete-subway/<int:pk>/delete', views.SubwayStationDeleteView.as_view(), name='delete-subway'),
    path('edit-subway/<int:pk>/update', views.SubwayStationUpdateView.as_view(), name='edit-subway'),
]

urlpatterns += [
    path('classrooms/', views.ClassroomListView.as_view(), name='classrooms'),
    path('classroom/<int:pk>/detail', views.ClassroomDetailView.as_view(), name='classroom-detail'),
    path('add-classroom/', views.ClassroomCreateView.as_view(), name='add-classroom'),
    path('delete-classroom/<int:pk>/delete', views.ClassroomDeleteView.as_view(), name='delete-classroom'),
    path('edit-classroom/<int:pk>/update', views.ClassroomUpdateView.as_view(), name='edit-classroom'),
]

schedule_planner_be/schedule_planner_be/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from .swagger import urlpatterns as doc_urls
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', TemplateView.as_view(template_name='User/home.html'), name='home'),
    path('courses/', include('course.urls')),
    path('teachers/', include('Teacher.urls')),
    path('user/', include('User.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/', include('api.urls')),
    path("schedule/", include('schedule.urls')),
]

urlpatterns += doc_urls

urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        )

schedule_planner_be/schedule/models.py
from datetime import time, datetime, timedelta, date
import time
# import pytz

from django.db import models
from django.db.models.signals import post_save, post_delete, pre_save
from django.dispatch import receiver
from django.urls import reverse
# from django_agenda.models import AbstractTimeSlot, AbstractAvailabilityOccurrence, AbstractAvailability, AbstractBooking
# from django_agenda.time_span import TimeSpan

# from User.models import User
from User.models import User
from course.models import Course, Comment, Lesson, ClassroomAvailability


# from schedule_planner_be import settings


class SubwayStation(models.Model):
    """Creates model Subway station"""
    station = models.CharField('Subway station', max_length=50, default=None)

    def __str__(self):
        return f"с/м {self.station}"

    class Meta:
        verbose_name = 'Станция метро'
        verbose_name_plural = 'Станции метро'


class Location(models.Model):
    """"Creates model Location"""
    city = models.CharField('City', max_length=50)
    street = models.CharField('Street', max_length=50)
    building = models.CharField('Building', max_length=10, default=None)
    subway = models.ForeignKey(SubwayStation, on_delete=models.SET_NULL, null=True, verbose_name='Станции метро')

    def __str__(self):
        return f"{self.street}, {self.building}, {self.subway}, {self.city}"

    class Meta:
        verbose_name = 'Локация'
        verbose_name_plural = 'Локации'


class Classroom(models.Model):
    """Creates model Classroom"""
    classroom = models.CharField('Classroom', max_length=10)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True)
    seats_number = models.PositiveSmallIntegerField("Number of seats")
    pc_number = models.PositiveSmallIntegerField("Number of PCs")

    def __str__(self):
        return f"ауд. {self.classroom}, {self.location}"

    class Meta:
        verbose_name = 'Аудитория'
        verbose_name_plural = 'Аудитории'
        unique_together = ('classroom', 'location')


# class Availability(AbstractAvailability):
#     class AgendaMeta:
#         schedule_model = Classroom
#         schedule_field = "classroom"  # optional


# class AvailabilityOccurrence(AbstractAvailabilityOccurrence):
#     class AgendaMeta:
#         availability_model = Availability
#         schedule_model = Classroom
#         schedule_field = "classroom"  # optional
#
#
# class TimeSlot(AbstractTimeSlot):
#     class AgendaMeta:
#         availability_model = Availability
#         schedule_model = Classroom
#         booking_model = "ClassroomReservation"  # booking class, more details shortly
#         schedule_field = "classroom"  # optional


# class ClassroomReservation(AbstractBooking):
#     class AgendaMeta:
#         schedule_model = Classroom
#
#     owner = models.ForeignKey(
#         to=settings.AUTH_USER_MODEL,
#         on_delete=models.PROTECT,
#         related_name="reservations",
#     )
#     start_time = models.DateTimeField(db_index=True)
#     end_time = models.DateTimeField(db_index=True)
#     approved = models.BooleanField(default=False)
#
#     def get_reserved_spans(self):
#         # we only reserve the time if the reservation has been approved
#         if self.approved:
#             yield TimeSpan(self.start_time, self.end_time)


# @receiver(post_save, sender=Classroom)
# def classroom_availability(sender, instance, **kwargs):
#     start_range_date = date(2022, 9, 1)
#     number_of_days = 365
#     date_list = []
#     for day in range(number_of_days):
#         a_date = (start_range_date + timedelta(days=day)).isoformat()
#         date_list.append(a_date)
#     start_time = time(8)
#     end_time = time(22)
#     tz = pytz.timezone("Europe/Minsk")
#     classroom = instance
#     for item in date_list:
#         # available from 8 AM to 22 PM
#         Availability.objects.create(
#             classroom=classroom,
#             start_date=item,
#             start_time=start_time,
#             end_time=end_time,
#             timezone=tz,
#         )


class Schedule(models.Model):
    """Создание модели Расписание"""

    title = models.TextField(default=None)
    courses = models.ForeignKey(Course, on_delete=models.DO_NOTHING, verbose_name='Курсы')
    locations = models.ForeignKey(Location, on_delete=models.DO_NOTHING, verbose_name='Локации')
    reviews = models.ForeignKey(Comment, on_delete=models.DO_NOTHING, verbose_name='Комментарии')
    url = models.SlugField(max_length=160, unique=True, default=None)

    def get_absolute_url(self):
        return reverse('course-detail', args=[str(self.id)])

    def __str__(self):
        return f"{self.courses}"

    class Meta:
        verbose_name = 'Расписание'
        verbose_name_plural = 'Расписания'


# class ClassroomAvailability(models.Model):
#     date = models.DateField()
#     classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)
#     start_time = models.CharField('Время начала занятия', max_length=5)
#     is_free = models.BooleanField(default=True)
#
#     class Meta:
#         verbose_name_plural = 'Все слоты аудитории'
#
#     def __str__(self):
#         return f"{self.date} {self.classroom} {self.start_time} {self.is_free}"


@receiver(post_save, sender=Classroom)
def classroom_availability(sender, instance, **kwargs):
    start_range_date = date(2022, 9, 1)
    number_of_days = 90
    date_list = []
    for day in range(number_of_days):
        a_date = (start_range_date + timedelta(days=day)).isoformat()
        date_list.append(a_date)
    classroom = instance
    start_time_range = ["08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00",
                        "16:00", "17:00", "18:00", "19:00", "20:00", "21:00"]
    for item in date_list:
        for start_time_option in start_time_range:
            # available from 8 AM to 22 PM
            ClassroomAvailability.objects.create(
                classroom=classroom,
                date=item,
                start_time=start_time_option,
            )


@receiver(post_save, sender=Lesson)
def reserve_classroom(sender, instance, **kwargs):
    lesson = instance
    date = lesson.date
    classroom = lesson.location
    print(classroom)
    start_time = lesson.start_time
    slot = ClassroomAvailability.objects.filter(date=date, classroom=classroom, start_time=start_time)
    print(slot)
    slot.update(is_free=False)
    print(slot)


@receiver(post_save, sender=Lesson)
def delete_old_classroomavailabilities(sender, instance, **kwargs):
    today = date.today()
    ClassroomAvailability.objects.filter(date__lt=today).delete()


@receiver(post_delete, sender=Lesson)
def make_classroomavailability_free(sender, instance, **kwargs):
    lesson = instance
    date = lesson.date
    classroom = lesson.location
    start_time = lesson.start_time
    slot = ClassroomAvailability.objects.filter(date=date, classroom=classroom, start_time=start_time)
    slot.update(is_free=True)


@receiver(post_delete, sender=Classroom)
def delete_classroomavailibility(sender, instance, **kwargs):
    classroom = instance
    location = classroom.location
    classroom = classroom.classroom
    address = f'ауд. {classroom}, {location}'
    ClassroomAvailability.objects.filter(classroom=address).delete()

# @receiver(post_save, sender=Lesson)
# def create_classroomreservation(sender, instance, **kwargs):
#     lesson = instance
#     user = lesson.created_by
#     print(user)
#     year = lesson.date.year
#     print(year, type(year))
#     month = lesson.date.month
#     day = lesson.date.day
#     print(day, type(day))
#     start_hour = int(lesson.start_time[:2])
#     print(start_hour, type(start_hour))
#     end_hour = lesson.end_time.hour
#     print(end_hour, type(end_hour))
#     tz = pytz.timezone("Europe/Minsk")
#     reservation = ClassroomReservation(
#         owner=user,
#         start_time=datetime(year=year, month=month, day=day, hour=start_hour, tzinfo=tz),
#         end_time=datetime(year=year, month=month, day=day, hour=end_hour, tzinfo=tz),
#     )
#     print(reservation, type(reservation))
#     reservation.clean()
#     reservation.save()


# def update():
#     while True:
#         now = datetime.now()
#         td = timedelta(days=1)
#         date = now + td
#         if now.hour == 10 and now.minute == 34:
#             all_classrooms = [classroom for classroom in Classroom.objects.all()]
#             print(all_classrooms)
#             for classroom in all_classrooms:
#                 start_time_range = ["08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00",
#                                     "16:00", "17:00", "18:00", "19:00", "20:00", "21:00"]
#                 for start_time_option in start_time_range:
#                     ClassroomAvailability.objects.create(
#                         classroom=classroom,
#                         date=date,
#                         start_time=start_time_option,
#                     )
#             time.sleep(24 * 60 * 60 - 120)
#         else:
#             time.sleep(15)

schedule_planner_be/schedule/forms.py
from django.forms import ModelForm
from .models import Schedule, Location, SubwayStation, Classroom


class ScheduleForm(ModelForm):
    class Meta:
        model = Schedule
        fields = '__all__'


class LocationForm(ModelForm):
    class Meta:
        model = Location
        fields = '__all__'


class SubwayStationForm(ModelForm):
    class Meta:
        model = SubwayStation
        fields = ['station', ]


class ClassroomForm(ModelForm):
    class Meta:
        model = Classroom
        fields = '__all__'

schedule_planner_be/api/classroom/views.py
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework import viewsets, renderers

from api.classroom.permissions import ClassroomPermissionsMixin
from api.classroom.serializers import ClassroomSerializer
from schedule.models import Classroom


class ClassroomViewSet(viewsets.ModelViewSet):
    """
    This viewset automatically provides `list`, `create`, `retrieve`,
    `update` and `destroy` actions.

    Additionally we also provide an extra `highlight` action.
    """
    queryset = Classroom.objects.all()
    serializer_class = ClassroomSerializer

    def get_permissions(self):
        """
        Instantiates and returns the list of permissions that this view requires.
        """
        if self.action == 'list':
            permission_classes = [IsAuthenticated]
        else:
            permission_classes = [IsAuthenticated & ClassroomPermissionsMixin]
        return [permission() for permission in permission_classes]

schedule_planner_be/api/location/views.py
from rest_framework import viewsets
from api.location.serializers import LocationSerializer
from schedule.models import Location
from api.location.permissions import LocationPermissionsMixin
from rest_framework.permissions import IsAuthenticated


class LocationViewSet(viewsets.ModelViewSet):
    queryset = Location.objects.all()
    serializer_class = LocationSerializer

    def get_permissions(self):
        """
        Instantiates and returns the list of permissions that this view requires.
        """
        if self.action == 'list':
            permission_classes = [IsAuthenticated]
        else:
            permission_classes = [IsAuthenticated & LocationPermissionsMixin]
        return [permission() for permission in permission_classes]

schedule_planner_be/api/schedule/views.py
from rest_framework import generics
from api.schedule.serializer import ScheduleListSerializer
from schedule.models import Schedule


class ScheduleListView(generics.ListAPIView):
    """Вывод списка расписания"""
    serializer_class = ScheduleListSerializer

    def get_queryset(self):
        schedules = Schedule.objects.all()
        return schedules


class ScheduleDetailsView(generics.RetrieveAPIView):
    """Вывод полного описания курса"""
    queryset = Schedule.objects.filter()
    serializer_class = ScheduleListSerializer

# class CourseCreateView(generics.CreateAPIView):
#     """Добавление курса"""
#     serializer_class = CourseCreateSerializer

schedule_planner_be/templates/schedule/add-location.html
{% extends 'layout/basic.html' %}
{% load crispy_forms_tags %}

{% block title %}Добавить место проведения курсов :: Локации{% endblock %}

{% block content %}
<h1>Добавить локации</h1>
<form action='' method='post'>
    {% csrf_token %}
    {{ form|crispy }}
    <input type='submit' value='Добавить'>
</form>
{% endblock %}

schedule_planner_be/templates/schedule/add-schedule.html
{% extends 'layout/basic.html' %}
{% load crispy_forms_tags %}

{% block title %}Добавить в расписание курс :: Расписание курсов{% endblock %}

{% block content %}
<h1>Добавить в расписание курс</h1>
<form action='' method='post'>
    {% csrf_token %}
    {{ form|crispy }}
    <input type='submit' value='Добавить'>
</form>
{% endblock %}

schedule_planner_be/templates/schedule/add-subway.html
{% extends 'layout/basic.html' %}
{% load crispy_forms_tags %}

{% block title %}Добавить станцию метро :: Метро{% endblock %}

{% block content %}
<h1>Добавить станцию метро</h1>
<form action='' method='post'>
    {% csrf_token %}
    {{ form|crispy }}
    <input type='submit' value='Добавить'>
</form>
{% endblock %}

schedule_planner_be/templates/schedule/classroom-detail.html
{% extends 'layout/basic.html' %}

{% block title %}Информация об аудитории :: Аудитория{% endblock %}

{% block content %}
    <h1>Аудитория: {{ classroom }}</h1>
    <p>
        <a href="{% url 'add-classroom' %}">
            <button
            type="button" class="btn btn-dark"><i class="bi bi-file-earmark-plus">ДОБАВТЬ</i>
            </button>
        </a>
        <a href="{% url 'edit-classroom' classroom.pk %}">
            <button
            type="button" class="btn btn-dark"><i class="bi bi-file-earmark-plus">ПРАВИТЬ</i>
            </button>
        </a>
        <a href="{% url 'delete-classroom' classroom.pk %}">
            <button
            type="button" class="btn btn-dark"><i class="bi bi-file-earmark-plus">УДАЛИТЬ</i>
            </button>
        </a>
    </p>
{% endblock %}

schedule_planner_be/templates/schedule/classrooms.html
{% extends 'layout/basic.html' %}

{% block title %}Classroom{% endblock %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Classrooms</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
            <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'add-classroom' %}">Add classroom</a></button>
        </div>
        <div class="btn-group me-2">
            <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'add-location' %}">Add location</a></button>
        </div>
    </div>
</div>
{% if classroom_list %}
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th scope="col">Number</th>
                    <th scope="col">Location</th>
                    <th scope="col">Seats number</th>
                    <th scope="col">PC number</th>
                    <th scope="col">Actions to classroom</th>
                </tr>
            </thead>
            {% for classroom in classroom_list %}
            <tbody>
                <tr>
                    <td>{{ classroom.classroom }}</td>
                    <td>{{ classroom.location }}</td>
                    <td>{{ classroom.seats_number }}</td>
                    <td>{{ classroom.pc_number }}</td>
                    <td>
                        <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'classroom-detail' classroom.pk %}">View</a></button>
                        <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'edit-classroom' classroom.pk %}">Edit</a></button>
                        <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'delete-classroom' classroom.pk %}">Delete</a></button>
                    </td>
                </tr>
            </tbody>
            {% endfor %}
        </table>
    </div>
{% else %}
    <p>Classroom doesn't exists</p>
{% endif %}
{% endblock %}

schedule_planner_be/templates/schedule/delete-location.html
{% extends 'layout/basic.html' %}

{% block title %}Удалить место расположения из локаций :: Локации{% endblock %}

{% block content %}
<h1>Вы уверены, что хотите удалить локацию {{ location }}?</h1>
<form method='post'>
    {% csrf_token %}
    <input type='submit' value='Удалить'>
</form>
{% endblock %}

schedule_planner_be/templates/schedule/delete-subway.html
{% extends 'layout/basic.html' %}

{% block title %}Удалить станцию метро :: Метро{% endblock %}

{% block content %}
<h1>Вы уверены, что хотите удалить станцию метро {{ subwaystation }}?</h1>
<form method='post'>
    {% csrf_token %}
    <input type='submit' value='Удалить'>
</form>
{% endblock %}

schedule_planner_be/templates/schedule/edit-classroom.html
{% extends 'layout/basic.html' %}
{% load crispy_forms_tags %}

{% block title %}Обновить информацию об аудитории :: Метро{% endblock %}

{% block content %}
<h1>Обновить информацию по аудитории</h1>
<form action='' method='post'>
    {% csrf_token %}
    {{ form|crispy }}
    <input type='submit' value='Обновить'>
</form>
{% endblock %}

schedule_planner_be/templates/schedule/edit-schedule.html
{% extends 'layout/basic.html' %}
{% load crispy_forms_tags %}

{% block title %}Обновить информацию по курсу :: Расписание курсов{% endblock %}

{% block content %}
<h1>Обновить информацию по курсу</h1>
<form action='' method='post'>
    {% csrf_token %}
    {{ form|crispy }}
    <input type='submit' value='Обновить'>
</form>
{% endblock %}

schedule_planner_be/templates/schedule/edit-subway.html
{% extends 'layout/basic.html' %}
{% load crispy_forms_tags %}

{% block title %}Обновить информацию о станции метро :: Метро{% endblock %}

{% block content %}
<h1>Обновить информацию по станции метро</h1>
<form action='' method='post'>
    {% csrf_token %}
    {{ form|crispy }}
    <input type='submit' value='Обновить'>
</form>
{% endblock %}

schedule_planner_be/templates/schedule/locations.html
{% extends 'layout/basic.html' %}

{% block title %}Location{% endblock %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Locations</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
            <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'add-classroom' %}">Add classroom</a></button>
        </div>
        <div class="btn-group me-2">
            <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'add-location' %}">Add location</a></button>
        </div>
    </div>
</div>
{% if location_list %}
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th scope="col">City</th>
                    <th scope="col">Street</th>
                    <th scope="col">Building</th>
                    <th scope="col">Subway</th>
                    <th scope="col">Actions to location</th>
                </tr>
            </thead>
            {% for location in location_list %}
            <tbody>
                <tr>
                    <td>{{ location.city }}</td>
                    <td>{{ location.street }}</td>
                    <td>{{ location.building }}</td>
                    <td>{{ location.subway }}</td>
                    <td>
                        <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'location-detail' location.pk %}">View</a></button>
                        <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'edit-location' location.pk %}">Edit</a></button>
                        <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'delete-location' location.pk %}">Delete</a></button>
                    </td>
                </tr>
            </tbody>
            {% endfor %}
        </table>
    </div>
{% else %}
    <p>Location doesn't exists.</p>
{% endif %}
{% endblock %}

schedule_planner_be/templates/schedule/schedule-detail.html
{% extends 'layout/basic.html' %}

{% block title %}Просмотреть детали расписания :: Расписание курсов{% endblock %}

{% block content %}
    <h1>Название курса: {{ schedule.course }}</h1>
    <p><strong>Расположение:</strong> {{ schedule.location }}</p>
    <p><strong>Преподаватель:</strong> {{ schedule.teacher }}
    <p><strong>Комментарий:</strong> {{ schedule.comment }}
    <p>
        <a href="{% url 'add-schedule' %}">
            <button
            type="button" class="btn btn-dark"><i class="bi bi-file-earmark-plus">ДОБАВТЬ</i>
            </button>
        </a>
        <a href="{% url 'edit-schedule' schedule.pk %}">
            <button
            type="button" class="btn btn-dark"><i class="bi bi-file-earmark-plus">ПРАВИТЬ</i>
            </button>
        </a>
        <a href="{% url 'delete-schedule' schedule.pk %}">
            <button
            type="button" class="btn btn-dark"><i class="bi bi-file-earmark-plus">УДАЛИТЬ</i>
            </button>
        </a>
    </p>
{% endblock %}

schedule_planner_be/templates/schedule/schedules.html
{% extends 'layout/basic.html' %}

{% block title %}Расписание курсов{% endblock %}

{% block content %}
    <h1>Расписание курсов</h1>

    {% if schedule_list %}
    <ul>
        {% for schedule in schedule_list %}
        <li>
            <a href="{{ schedule.get_absolute_url }}">{{ schedule.course }}</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>В расписание пока еще не добавлены курсы</p>
    {% endif %}
{% endblock %}

schedule_planner_be/templates/schedule/subway-detail.html
{% extends 'layout/basic.html' %}

{% block title %}Информация о станции метро :: Метро{% endblock %}

{% block content %}
    <h1>Станция метро: {{ subwaystation }}</h1>
    <p>
        <a href="{% url 'add-subway' %}">
            <button
            type="button" class="btn btn-dark"><i class="bi bi-file-earmark-plus">ДОБАВТЬ</i>
            </button>
        </a>
        <a href="{% url 'edit-subway' subwaystation.pk %}">
            <button
            type="button" class="btn btn-dark"><i class="bi bi-file-earmark-plus">ПРАВИТЬ</i>
            </button>
        </a>
        <a href="{% url 'delete-subway' subwaystation.pk %}">
            <button
            type="button" class="btn btn-dark"><i class="bi bi-file-earmark-plus">УДАЛИТЬ</i>
            </button>
        </a>
    </p>
{% endblock %}